### ISSUE TITLE
Select2 widget not initialised when not on default tab plone 5

### ISSUE THREAD

**Issue by Nachtalb** [4teamwork/ftw.keywordwidget#42]
![image](https://user-images.githubusercontent.com/9467802/67859646-6abdf200-fb1c-11e9-8119-a3526a7849b5.png)

This is a case of javascript not initializing the widget is not in the tab that is loaded on page load. Meaning if you open the `/edit` form in the above's second case then the `Standard` tab is loaded and the widget is not initialized. If you then change to the `Kategorisierung` tab and reload the page, this tab will be the first to load and the javascript will initialize the widget.

**Comment by maethu** [comment]
To solve this issue, we something like https://github.com/4teamwork/ftw.simplelayout/blob/master/ftw/simplelayout/mapblock/browser/resources/mapblock.js#L109

initi the select2 after clicking on a tab (for plone4 and plone5)

**Comment by maethu** [comment]
Invest max 4h

**Comment by djowett-ftw** [comment]
Resolved by #47
