### ISSUE TITLE
Select2 is not installed

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.keywordwidget#43]
The select2 JavaScript is not registered in the default GS profile, but in a separate one. That means when I install `ftw.keywordwidget` it will not work it will not work and I get a JavaScript error that `.select2` is not defined.

I suggest to move the JS registration into the default profiles and eliminate the separate `select2` profile which is not Plone 5 compatible anyways.

@maethu any objections?

/cc @tinagerber

**Comment by maethu** [comment]
The problem with plone 5 is that they ship a older select2 version which is not compatible with ftw.keywordwidget. If we ship select2 directly for plone5 we need to make sure it's isolated only for the keywordwidget 

The ftw.keywordwidget requires at least 4.0.2, but plone provides 3.5.x which has breaking API changes regarding this widget.

**Comment by jone** [comment]
@maethu but the current implementation simply does not work. For instance: when I install `ftw.news` I cannot create a news listing block.
That means we probably need to ship our own isolated version then.

**Comment by maethu** [comment]
@jone Yes that's probably the best solution, updating the one from Plone is probably not really possible. 

It just kinda suck to have an isolated one... but well, that way we can get it run again.

**Comment by maethu** [comment]
ohh we may have to patch it to be isolated, since it registers itself globally 😢 
Maybe unter ftwSelect2

**Comment by maethu** [comment]
@jone We do already install select2 locally? --> https://github.com/4teamwork/ftw.keywordwidget/blob/master/ftw/keywordwidget/resources/js/keywordwidget_5.x.js

**Comment by jone** [comment]
> @jone We do already install select2 locally? --> https://github.com/4teamwork/ftw.keywordwidget/blob/master/ftw/keywordwidget/resources/js/keywordwidget_5.x.js

Yes, but it is not installed in the js registry in the default profile. I _can_ install the custom select2 profile, if I know that it exists, but if I just install the default profile it wont work.

Why is there a separate `select2` GS profile?

**Comment by maethu** [comment]
The select2 profile is unusable in pone5 (Should not be installable). 
In https://github.com/4teamwork/ftw.keywordwidget/blob/master/ftw/keywordwidget/profiles/default_plone5/registry.xml#L5 there ist the actual implementation and an isolated select2

**Comment by jone** [comment]
The problem is that multiple ftw-packages use select2, but the JS can only be loaded once because it will break otherwise. Thus, adding the select2 JS in multiple packages will not work and therefore we have the approach that an integrator has to do that once for a project.

It is documented in the readme: https://github.com/4teamwork/ftw.keywordwidget#usage--integration

/cc @busykoala
